### ISSUE TITLE
BUG REPORT

### ISSUE THREAD

**Issue by tombelieber** [sammychinedu2ky/vscodeExtension-prisma-schema-tool#2]
work for 2 words, not working for 3 words.

**Comment by tombelieber** [comment]
![Uploading Screen Shot 2021-01-04 at 12.04.21 PM.png…]()

**Comment by sammychinedu2ky** [comment]
Thanks for the notification. Please can you post a picture of what it looks like

**Comment by tombelieber** [comment]
![Screen Shot 2021-01-04 at 3 12 45 PM](https://user-images.githubusercontent.com/47057684/103510024-57848000-4e9f-11eb-8a2b-53009e4eafdc.png)

**Comment by sammychinedu2ky** [comment]
Buts seems to be working well in three words from your picture

**Comment by tombelieber** [comment]
It would be better if it could handle the camelCase of 3 words
e.g.
`positionInSchool` 
I was using `positionInSchool` originally, after conversion, it became `positionInschool`

**Comment by sammychinedu2ky** [comment]
From my end, I tried the code below before conversion.
```
model country {
  id           String    @id
  alpha2_code  String    @unique
  alpha3_code  String    @unique
  name         String    @unique
  positionInSchool      String?
  continent_id String
  continent    Continent @relation(fields: [continent_id], references: [id])
}
```

and got this after conversion
```
model country {
  id           String    @id
  alpha2Code  String    @unique @map("alpha2_code")
  alpha3Code  String    @unique @map("alpha3_code")
  name         String    @unique
  positionInSchool      String?
  continentId String @map("continent_id")
  continent    Continent @relation(fields: [continentId], references: [id])
}


```

It didn't affect positionInSchool.  Please can you write your issue in this manner and also tell me what you expect it to be. Thanks for telling me about this as I would like to see it resolved.
